### ISSUE TITLE
[ENH] Sanity check subjects in H5 against phenotyping csv

### ISSUE THREAD

**Issue by TinasheMTapera** [PennLINC/ModelArray#5]
Have to make sure the phenotypes csv will match the actual h5 contents

enhanced version: check the consistency of mif filename, instead of subject id (as there could also be session id...)
- [x] ConFixel: make sure mif file is written
- [x] ModelArray: update

- [x] test out dataset with more than one scalar type (see tests for ModelArray class)
  - [x] ConFixel: subject list is good?
  - [x] ModelArray: scalars's column names and ids are good?
- [x] Functions to add sanity check of subject list:
  - [x] ModelArray.lm()
  - [x] ModelArray.gam()
- [x] Add corresponding tests

**Comment by zhao-cy** [comment]
- [ ] ConFixel: .mif --> .h5: subject IDs need to be written
- [ ] FixelArray: compare subject ID list in fixel data (.h5) with those in .csv
