### ISSUE TITLE
[REVIEW] docs for developer + main pages of ModelArray & ConFixel

### ISSUE THREAD

**Issue by zhao-cy** [PennLINC/ModelArray#66]
quickly go thru:

- [x] [docs for developer](https://pennlinc.github.io/ModelArray/articles/doc_for_developer.html)
  - [x] most important is the section [model fitting](https://pennlinc.github.io/ModelArray/articles/doc_for_developer.html#model-fitting)
- [x] [main page of ModelArray](https://github.com/PennLINC/ModelArray)
- [x] [main page of ConFixel](https://github.com/PennLINC/ConFixel)

The latest version has been merged into main, and has been deployed i.e.,  can be directly viewed with the links above

**Comment by TinasheMTapera** [comment]
Done, no major comments
